# Generated by Django 4.1.5 on 2023-01-10 01:38

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('cost_per_liter', models.DecimalField(decimal_places=2, max_digits=10)),
                ('flow_volume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('Pilsen', 'Pilsen'), ('Lager', 'Lager'), ('Ipa', 'Ipa'), ('Stout', 'Stout'), ('Weiss', 'Weiss'), ('Apa', 'Apa'), ('Pale Ale', 'Pale Ale')], max_length=100)),
                ('image', stdimage.models.StdImageField(force_min_size=False, upload_to='beer_pictures', variations={'thumb': {'crop': True, 'height': 200, 'width': 100}})),
                ('times_used', models.DecimalField(decimal_places=2, max_digits=1000)),
            ],
        ),
    ]
