# Generated by Django 4.1.5 on 2023-01-12 00:19

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='image',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to='beer_pictures', variations={'thumb': {'crop': True, 'height': 100, 'width': 50}}),
        ),
        migrations.AlterField(
            model_name='beer',
            name='times_used',
            field=models.IntegerField(default=0),
        ),
    ]
