# Generated by Django 4.1.5 on 2023-01-17 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_beer_image_alter_beer_times_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
